// <auto-generated />
namespace Quizz.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class LinkQuizz3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LinkQuizz3));
        
        string IMigrationMetadata.Id
        {
            get { return "201909251214551_LinkQuizz3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
